scurvy <- read.table("scurvy.csv", header = TRUE, sep = ',')
summary(scurvy)
str(scurvy)
scurvy$treatment <- factor(scurvy$treatment)
scurvy$gum_rot_d6 <- factor(scurvy$gum_rot_d6)
scurvy$skin_sores_d6 <- factor(scurvy$skin_sores_d6)
table(scurvy$study_id, scurvy$gum_rot_d6)
table (scurvy$study_id, scurvy$weakness_of_the_knees_d6)
boxplot(scurvy$gum_rot_d6 ~ scurvy$treatment, data = scurvy, cex.axis = 1.2, xlab = "", ylab = "")
stripchart(scurvy$gum_rot_d6 ~ scurvy$treatment, data = scurvy, add = TRUE, vertical = TRUE, method = "jitter", pch = 21, col = "maroon", bg = "bisque")
scurvy$treatment <- factor(scurvy$treatment)
boxplot(scurvy$weakness_of_the_knees_d6 ~ scurvy$treatment, data = scurvy, cex.axis = 1.2, xlab = "", ylab = "")
stripchart(scurvy$weakness_of_the_knees_d6 ~ scurvy$treatment, data = scurvy, add = TRUE, vertical = TRUE, method = "jitter", pch = 21, col = "maroon", bg = "bisque")
